services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newsletter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node-app:
    build: .
    container_name: feria-node
    restart: always
    depends_on:
      - mysql-db
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data  # ðŸ‘ˆ si tu CSV estÃ¡ en /data
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env  # ðŸ‘ˆ cargamos variables desde aquÃ­

volumes:
  mysql-data:
